### PR TITLE
Add a sudoku benchmark

### PR DESCRIPTION
**Pull request by tonybaloney**
Credit @stonebig

### CODE REVIEW

**Comment by stonebig** [comment]
hum, this part of the documentation seems not working in pyjion-1.1.0
image

launching via pyjion fails (!?) on my PC.

so using this:
```
import pyjion
pyjion.config(level=2)
pyjion.enable()
```

**Comment by stonebig** [comment]
on an old i5-3317U cpu, pyjion-1.1.0 level 2 doesn't seem to make an impact.

what is strange is the Memory occupation of the process continuously increasing along the computation, like if there was a memory leak (of whatever).

memory use:
- cpython: 5.7 Mo (and constant)
- pyjion (+1Mo per second all along)

**Comment by tonybaloney** [comment]
Which operating system?

**Comment by stonebig** [comment]
Windows 10 21H1 64bit

**Pull request merged**
