### PR TITLE
Add tests for reference leaks in function calls to CFunction objects

### PR DESCRIPTION
**Pull request by tonybaloney**
CC @tetsuo-cpp this is how I'm going to test the other path.

Any module in the `Modules/` path, which I can find an appropriate argument signature for the number of arguments required. 
Testing both a happy path and a path which raises an exception is critical.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
@tonybaloney Cool. It actually shows a reference leak in CI for the 15 args example. Hopefully, my PR that decrements the ref counts for the vector call fixes that.

**Comment by tonybaloney** [comment]
> @tonybaloney Cool. It actually shows a reference leak in CI for the 15 args example. Hopefully, my PR that decrements the ref counts for the vector call fixes that.

Its failing on linux and passing on Windows :-#

**Comment by tonybaloney** [comment]
Also, that test case which is failing will call `PyJit_CallN()`

**Comment by tonybaloney** [comment]
I'm pretty confident this bug is in the way that `PyJit_CallN` works. I'm going to reuse your code from `MethCallN` and rewrite it

**Pull request merged**
