### PR TITLE
Decrement args after method vector call

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
@tonybaloney 
I don't think that the test failures were due to the reference leak I mentioned. The reference count is the same before and after the function call.

Because of the `PyCFunction_Check`, the vector call code path isn't getting exercised in these Python tests.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
Hmm, this passes locally for me. Not sure what's going on.

**Comment by tonybaloney** [comment]
> I've just temporarily pointed the PR at `master` to get it to kick off a CI build.
> 
> Not sure what's happening with the failure. It passes locally for me... I'll take a look when I get the chance.



> @tonybaloney
> I don't think that the test failures were due to the reference leak I mentioned. The reference count is the same before and after the function call.
> 
> Because of the `PyCFunction_Check`, the vector call code path isn't getting exercised in these Python tests.

I hope that is the case because I've been trying to track down this stupid bug for weeks! I'm going to write tests calling C functions this morning.

In the meantime, can you retarget this PR at the other branch?

**Comment by tetsuo-cpp** [comment]
Ok, retargeted.

Yeah, it looks like the CI machine is getting a different ref count from what I see locally. But still, the number appears to be unchanged before and after the function call (just the number itself is different when I test locally).

**Comment by tonybaloney** [comment]
> Ok, retargeted.
> 
> Yeah, it looks like the CI machine is getting a different ref count from what I see locally which is why it's failing. But still, the number appears to be unchanged before and after the function call (just the number itself is different when I test locally).

I've stopped hardcoding the references because its not an ideal way to do it. Instead just comparing the before and after of the target and the arguments. You can remove the hardcoded assertions

**Comment by tetsuo-cpp** [comment]
@tonybaloney Ok, I've removed the lines that were causing problems.

**Pull request merged**
